// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:4.0.0.0
//      SpecFlow Generator Version:4.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TrackListTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Реєстрація користувача")]
    [NUnit.Framework.CategoryAttribute("epic1")]
    [NUnit.Framework.CategoryAttribute("auth")]
    public partial class РеєстраціяКористувачаFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "epic1",
                "auth"};
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerForAssembly(null, NUnit.Framework.TestContext.CurrentContext.WorkerId);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("uk-UA"), "Features", "Реєстрація користувача", "  Як Гість (неавторизований користувач),\r\n  Я хочу мати можливість зареєструвати " +
                    "новий обліковий запис,\r\n  Щоб отримати доступ до повного функціоналу сайту.", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            await testRunner.GivenAsync("Гість знаходиться на сторінці \"/register\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Успішна реєстрація нового користувача")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        [NUnit.Framework.CategoryAttribute("us-101")]
        public async System.Threading.Tasks.Task УспішнаРеєстраціяНовогоКористувача()
        {
            string[] tagsOfScenario = new string[] {
                    "happy-path",
                    "us-101"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Успішна реєстрація нового користувача", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Поле",
                            "Значення"});
                table1.AddRow(new string[] {
                            "Нікнейм",
                            "new_user"});
                table1.AddRow(new string[] {
                            "Email",
                            "user@example.com"});
                table1.AddRow(new string[] {
                            "Пароль",
                            "Password123"});
                table1.AddRow(new string[] {
                            "Підтвердження пароля",
                            "Password123"});
                table1.AddRow(new string[] {
                            "Ім\'я",
                            "Тест Тестенко"});
                table1.AddRow(new string[] {
                            "Вік",
                            "25"});
                table1.AddRow(new string[] {
                            "Стать",
                            "Чоловік"});
                table1.AddRow(new string[] {
                            "Країна",
                            "Україна"});
                await testRunner.AndAsync("Гість вводить наступні валідні дані:", ((string)(null)), table1, "І ");
                await testRunner.WhenAsync("Гість натискає кнопку \"Зареєструватися\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Система створює нового користувача \"new_user\" в базі даних", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Система хешує пароль користувача", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Користувач \"new_user\" автоматично авторизований", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Користувача перенаправлено на головну сторінку \"/\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Реєстрація з нікнеймом, що вже існує")]
        [NUnit.Framework.CategoryAttribute("negative-path")]
        [NUnit.Framework.CategoryAttribute("us-101")]
        public async System.Threading.Tasks.Task РеєстраціяЗНікнеймомЩоВжеІснує()
        {
            string[] tagsOfScenario = new string[] {
                    "negative-path",
                    "us-101"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Реєстрація з нікнеймом, що вже існує", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.AndAsync("В базі даних існує користувач з нікнеймом \"existing_user\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.WhenAsync("Гість намагається зареєструватися з нікнеймом \"existing_user\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Система не створює нового користувача", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Система показує повідомлення про помилку \"Цей нікнейм вже зайнятий\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Реєстрація з email, що вже існує")]
        [NUnit.Framework.CategoryAttribute("negative-path")]
        [NUnit.Framework.CategoryAttribute("us-101")]
        public async System.Threading.Tasks.Task РеєстраціяЗEmailЩоВжеІснує()
        {
            string[] tagsOfScenario = new string[] {
                    "negative-path",
                    "us-101"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Реєстрація з email, що вже існує", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.AndAsync("В базі даних існує користувач з email \"taken@example.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.WhenAsync("Гість намагається зареєструватися з email \"taken@example.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Система не створює нового користувача", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Система показує повідомлення про помилку \"Ця email-адреса вже зайнята\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Реєстрація з невідповідними паролями")]
        [NUnit.Framework.CategoryAttribute("negative-path")]
        [NUnit.Framework.CategoryAttribute("us-101")]
        public async System.Threading.Tasks.Task РеєстраціяЗНевідповіднимиПаролями()
        {
            string[] tagsOfScenario = new string[] {
                    "negative-path",
                    "us-101"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Реєстрація з невідповідними паролями", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("Гість вводить \"Password123\" в поле \"Пароль\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.AndAsync("Гість вводить \"Password456\" в поле \"Підтвердження пароля\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Гість натискає кнопку \"Зареєструватися\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("Система не створює нового користувача", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Система показує повідомлення про помилку \"Паролі не збігаються\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Реєстрація з паролем, що не відповідає політиці безпеки (BRL-2)")]
        [NUnit.Framework.CategoryAttribute("negative-path")]
        [NUnit.Framework.CategoryAttribute("us-101")]
        [NUnit.Framework.CategoryAttribute("brl-2")]
        public async System.Threading.Tasks.Task РеєстраціяЗПаролемЩоНеВідповідаєПолітиціБезпекиBRL_2()
        {
            string[] tagsOfScenario = new string[] {
                    "negative-path",
                    "us-101",
                    "brl-2"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Реєстрація з паролем, що не відповідає політиці безпеки (BRL-2)", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("Гість вводить пароль \"pass\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.AndAsync("Гість натискає кнопку \"Зареєструватися\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("Система не створює нового користувача", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Система показує повідомлення про помилку \"Пароль повинен містити щонайменше 8 сим" +
                        "волів, включаючи літери та цифри або спеціальні символи (!@#$%^&_-=+ і т.д.)\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Реєстрація з незаповненими обов\'язковими полями")]
        [NUnit.Framework.CategoryAttribute("negative-path")]
        [NUnit.Framework.CategoryAttribute("us-101")]
        public async System.Threading.Tasks.Task РеєстраціяЗНезаповненимиОбовязковимиПолями()
        {
            string[] tagsOfScenario = new string[] {
                    "negative-path",
                    "us-101"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Реєстрація з незаповненими обов\'язковими полями", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("Гість залишає поле \"Нікнейм\" порожнім", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.AndAsync("Гість залишає поле \"Email\" порожнім", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Гість залишає поле \"Пароль\" порожнім", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Гість натискає кнопку \"Зареєструватися\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("Система не створює нового користувача", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Система показує повідомлення про помилку \"Це поле є обов\'язковим\" біля поля \"Нікн" +
                        "ейм\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Система показує повідомлення про помилку \"Це поле є обов\'язковим\" біля поля \"Елек" +
                        "тронна пошта\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Система показує повідомлення про помилку \"Це поле є обов\'язковим\" біля поля \"Паро" +
                        "ль\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Реєстрація з використанням зарезервованого (системного) нікнейму")]
        [NUnit.Framework.CategoryAttribute("us-101")]
        [NUnit.Framework.CategoryAttribute("negative-path")]
        [NUnit.Framework.CategoryAttribute("security")]
        public async System.Threading.Tasks.Task РеєстраціяЗВикористаннямЗарезервованогоСистемногоНікнейму()
        {
            string[] tagsOfScenario = new string[] {
                    "us-101",
                    "negative-path",
                    "security"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Реєстрація з використанням зарезервованого (системного) нікнейму", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Гість знаходиться на сторінці \"/register\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Гість намагається зареєструватися з нікнеймом \"admin\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Система не створює нового користувача", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Система показує повідомлення про помилку \"Цей нікнейм зарезервовано. Будь ласка, " +
                        "оберіть інший.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Реєстрація з використанням зарезервованого нікнейму (інший регістр)")]
        [NUnit.Framework.CategoryAttribute("us-101")]
        [NUnit.Framework.CategoryAttribute("negative-path")]
        [NUnit.Framework.CategoryAttribute("security")]
        public async System.Threading.Tasks.Task РеєстраціяЗВикористаннямЗарезервованогоНікнеймуІншийРегістр()
        {
            string[] tagsOfScenario = new string[] {
                    "us-101",
                    "negative-path",
                    "security"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Реєстрація з використанням зарезервованого нікнейму (інший регістр)", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Гість знаходиться на сторінці \"/register\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Гість намагається зареєструватися з нікнеймом \"Moderator\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Система не створює нового користувача", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Система показує повідомлення про помилку \"Цей нікнейм зарезервовано. Будь ласка, " +
                        "оберіть інший.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Успішна авторизація (Логін)")]
        [NUnit.Framework.CategoryAttribute("us-102")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task УспішнаАвторизаціяЛогін()
        {
            string[] tagsOfScenario = new string[] {
                    "us-102",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Успішна авторизація (Логін)", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Гість знаходиться на сторінці \"/login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Гість вводить \"user\" в поле \"Нікнейм або Email\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.AndAsync("Гість вводить \"Password123\" в поле \"Пароль\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Гість натискає кнопку \"Увійти\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("Користувач \"user\" авторизований", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Користувача перенаправлено на головну сторінку \"/\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Успішна авторизація через Email")]
        [NUnit.Framework.CategoryAttribute("us-102")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task УспішнаАвторизаціяЧерезEmail()
        {
            string[] tagsOfScenario = new string[] {
                    "us-102",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Успішна авторизація через Email", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Гість знаходиться на сторінці \"/login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Гість вводить \"user@app.com\" в поле \"Нікнейм або Email\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.AndAsync("Гість вводить \"Password123\" в поле \"Пароль\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Невдала авторизація (Неправильний пароль)")]
        [NUnit.Framework.CategoryAttribute("us-102")]
        [NUnit.Framework.CategoryAttribute("negative-path")]
        public async System.Threading.Tasks.Task НевдалаАвторизаціяНеправильнийПароль()
        {
            string[] tagsOfScenario = new string[] {
                    "us-102",
                    "negative-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Невдала авторизація (Неправильний пароль)", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Гість знаходиться на сторінці \"/login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Гість вводить \"user\" в поле \"Нікнейм або Email\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.AndAsync("Гість вводить \"WrongPassword\" в поле \"Пароль\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Гість натискає кнопку \"Увійти\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("Користувач не авторизований", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Система показує повідомлення про помилку \"Неправильний логін або пароль\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Невдала авторизація (Користувач не існує)")]
        [NUnit.Framework.CategoryAttribute("us-102")]
        [NUnit.Framework.CategoryAttribute("negative-path")]
        public async System.Threading.Tasks.Task НевдалаАвторизаціяКористувачНеІснує()
        {
            string[] tagsOfScenario = new string[] {
                    "us-102",
                    "negative-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Невдала авторизація (Користувач не існує)", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Гість знаходиться на сторінці \"/login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Гість вводить \"non_existent_user\" в поле \"Нікнейм або Email\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.AndAsync("Гість вводить \"Password123\" в поле \"Пароль\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("Система показує повідомлення про помилку \"Неправильний логін або пароль\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Успішний вихід (Logout)")]
        [NUnit.Framework.CategoryAttribute("us-103")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task УспішнийВихідLogout()
        {
            string[] tagsOfScenario = new string[] {
                    "us-103",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Успішний вихід (Logout)", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Користувач \"user\" авторизований в системі", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Користувач натискає кнопку \"Вийти\" (наприклад, у своєму профілі)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Сесія користувача завершена", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Користувача перенаправлено на головну сторінку \"/\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
