// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:4.0.0.0
//      SpecFlow Generator Version:4.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TrackListTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Стрічка активності")]
    [NUnit.Framework.CategoryAttribute("epic3")]
    [NUnit.Framework.CategoryAttribute("feed")]
    public partial class СтрічкаАктивностіFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "epic3",
                "feed"};
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerForAssembly(null, NUnit.Framework.TestContext.CurrentContext.WorkerId);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("uk-UA"), "Features", "Стрічка активності", @"  Як Авторизований користувач,
  Я хочу бачити на головній сторінці стрічку рецензій від користувачів, на яких я підписаний,
  А також мати можливість взаємодіяти з цими рецензіями (лайкати, бачити топ-коментар)
  Щоб швидко реагувати на активність моїх підписок.", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            await testRunner.GivenAsync("В базі даних існують користувачі \"user\", \"following_1\", \"following_2\" та \"other_u" +
                    "ser\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
            await testRunner.AndAsync("Користувач \"user\" авторизований в системі", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("\"user\" підписаний на \"following_1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("\"user\" підписаний на \"following_2\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("\"user\" НЕ підписаний на \"other_user\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("\"following_1\" написав рецензію \"review_1\" на \"Медіа А\" (5 годин тому)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("\"review_1\" має \"15\" вподобайок", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("\"following_2\" написав рецензію \"review_2\" на \"Медіа Б\" (2 години тому)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("\"other_user\" написав рецензію \"review_3\" на \"Медіа В\" (1 годину тому)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("\"other_user\" залишив коментар \"comment_A\" (до \"review_1\") з \"5\" лайками", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("\"user\" залишив коментар \"comment_B\" (до \"review_1\") з \"2\" лайками", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Перегляд персоналізованої стрічки")]
        [NUnit.Framework.CategoryAttribute("us-301")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task ПереглядПерсоналізованоїСтрічки()
        {
            string[] tagsOfScenario = new string[] {
                    "us-301",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Перегляд персоналізованої стрічки", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("Користувач \"user\" відкриває головну сторінку (\"/\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Він бачить \"review_2\" (від \"following_2\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Він бачить \"review_1\" (від \"following_1\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("\"review_2\" знаходиться у стрічці вище, ніж \"review_1\" # Перевірка хронологічного " +
                        "порядку", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він НЕ бачить \"review_3\" (від \"other_user\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Перегляд персоналізованої стрічки (без підписок)")]
        [NUnit.Framework.CategoryAttribute("us-301")]
        [NUnit.Framework.CategoryAttribute("negative-path")]
        public async System.Threading.Tasks.Task ПереглядПерсоналізованоїСтрічкиБезПідписок()
        {
            string[] tagsOfScenario = new string[] {
                    "us-301",
                    "negative-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Перегляд персоналізованої стрічки (без підписок)", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Користувач \"new_user\" авторизований в системі", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.AndAsync("\"new_user\" ще ні на кого не підписаний", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.WhenAsync("\"new_user\" відкриває головну сторінку (\"/\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Він НЕ бачить жодної рецензії", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Він бачить повідомлення \"Ваша стрічка порожня. Підпишіться на когось або переглян" +
                        "ьте Глобальну стрічку.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Перегляд Глобальної стрічки")]
        [NUnit.Framework.CategoryAttribute("us-302")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task ПереглядГлобальноїСтрічки()
        {
            string[] tagsOfScenario = new string[] {
                    "us-302",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Перегляд Глобальної стрічки", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Користувач \"user\" авторизований в системі", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("\"user\" відкриває головну сторінку (\"/\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.AndAsync("\"user\" натискає на вкладку \"Глобальна стрічка\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("Він бачить \"review_3\" (від \"other_user\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Він бачить \"review_2\" (від \"following_2\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він бачить \"review_1\" (від \"following_1\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("\"review_3\" знаходиться у стрічці вище # Перевірка хронологічного порядку", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Вподобайка рецензії безпосередньо зі стрічки")]
        [NUnit.Framework.CategoryAttribute("us-303")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task ВподобайкаРецензіїБезпосередньоЗіСтрічки()
        {
            string[] tagsOfScenario = new string[] {
                    "us-303",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Вподобайка рецензії безпосередньо зі стрічки", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Користувач \"user\" авторизований і бачить \"review_1\" у своїй стрічці", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.AndAsync("\"review_1\" має \"15\" вподобайок", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("\"user\" ще не лайкнув \"review_1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.WhenAsync("Він натискає \"Вподобати\" (Like) на \"review_1\" у стрічці", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Лічильник вподобайок \"review_1\" оновлюється на \"16\" (у стрічці)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Кнопка змінює стан на \"Вподобано\" (Liked)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Користувач залишається на сторінці \"/\" (без перезавантаження)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Перегляд найзалайканішого коментаря у стрічці")]
        [NUnit.Framework.CategoryAttribute("us-304")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task ПереглядНайзалайканішогоКоментаряУСтрічці()
        {
            string[] tagsOfScenario = new string[] {
                    "us-304",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Перегляд найзалайканішого коментаря у стрічці", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Користувач \"user\" авторизований і бачить \"review_1\" у своїй стрічці", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Він дивиться на блок коментарів під \"review_1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Він бачить \"comment_A\" (від \"other_user\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Він бачить лічильник \"5\" вподобайок біля \"comment_A\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він НЕ бачить \"comment_B\" (який має менше лайків)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він бачить посилання \"Переглянути всі N коментарів...\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
