// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:4.0.0.0
//      SpecFlow Generator Version:4.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TrackListTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Сторінка медіа-контенту та взаємодія")]
    [NUnit.Framework.CategoryAttribute("epic4")]
    [NUnit.Framework.CategoryAttribute("media")]
    public partial class СторінкаМедіа_КонтентуТаВзаємодіяFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "epic4",
                "media"};
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerForAssembly(null, NUnit.Framework.TestContext.CurrentContext.WorkerId);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("uk-UA"), "Features", "Сторінка медіа-контенту та взаємодія", "  Як Користувач (або Гість),\r\n  Я хочу переглядати детальну інформацію про медіа-" +
                    "контент моєю мовою\r\n  Та пропонувати власні переклади, якщо офіційні відсутні аб" +
                    "о невірні.", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            await testRunner.GivenAsync("Існує медіа \"Dune\" (Id: 2)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
            await testRunner.AndAsync("Існує медіа \"Inception\" (Id: 3)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("В `MediaTranslations` існує: (MediaId: 2, Lang: \"en\", Title: \"Dune\", Description:" +
                    " \"English desc...\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("В `MediaTranslations` існує: (MediaId: 2, Lang: \"uk\", Title: \"Дюна\", Description:" +
                    " \"Український опис...\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("В `MediaTranslations` існує: (MediaId: 3, Lang: \"en\", Title: \"Inception\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("В базі даних існує користувач \"user\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("В базі даних існує користувач \"other_user\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("\"other_user\" написав рецензію \"review_1\" на \"Dune\" (Id: 2)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("\"other_user\" написав коментар \"comment_1\" до рецензії \"review_1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("Користувач \"user\" авторизований", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("Мова інтерфейсу користувача \"user\" встановлена на \"uk\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Користувач бачить сторінку медіа мовою свого інтерфейсу")]
        [NUnit.Framework.CategoryAttribute("us-401")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task КористувачБачитьСторінкуМедіаМовоюСвогоІнтерфейсу()
        {
            string[] tagsOfScenario = new string[] {
                    "us-401",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Користувач бачить сторінку медіа мовою свого інтерфейсу", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("Користувач \"user\" відкриває сторінку \"/media/2\" (Dune)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Він бачить заголовок \"Дюна\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Він бачить опис \"Український опис...\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він бачить рейтинги IMdB / Rotten Tomatoes", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він бачить список рецензій, включаючи \"review_1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Користувач бачить сторінку (дефолтна мова), якщо його мова відсутня")]
        [NUnit.Framework.CategoryAttribute("us-401")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task КористувачБачитьСторінкуДефолтнаМоваЯкщоЙогоМоваВідсутня()
        {
            string[] tagsOfScenario = new string[] {
                    "us-401",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Користувач бачить сторінку (дефолтна мова), якщо його мова відсутня", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Мова інтерфейсу користувача \"user\" встановлена на \"pl\" (Польська)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.AndAsync("Для \"Dune\" (Id: 2) не існує перекладу \"pl\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.WhenAsync("Користувач \"user\" відкриває сторінку \"/media/2\" (Dune)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Він бачить заголовок \"Dune\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Він бачить опис \"English desc...\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Користувач пише нову рецензію з rich-text")]
        [NUnit.Framework.CategoryAttribute("us-402")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        [NUnit.Framework.CategoryAttribute("rich-text")]
        public async System.Threading.Tasks.Task КористувачПишеНовуРецензіюЗRich_Text()
        {
            string[] tagsOfScenario = new string[] {
                    "us-402",
                    "happy-path",
                    "rich-text"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Користувач пише нову рецензію з rich-text", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Користувач \"user\" авторизований і знаходиться на \"/media/2\" (Dune)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.AndAsync("\"user\" ще не писав рецензію на \"Dune\" (Id: 2) (згідно з BRL-4)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.WhenAsync("Він ставить оцінку \"5 зірок\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.AndAsync("Він вводить в \"rich-text\" редактор текст: \"Це **чудовий** фільм!\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він натискає кнопку \"Опублікувати рецензію\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("Система зберігає нову рецензію з HTML/Markdown (\"<p>Це <strong>чудовий</strong> ф" +
                        "ільм!</p>\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Його рецензія з\'являється у списку рецензій на сторінці", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він бачить повідомлення \"Рецензію опубліковано\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Користувач намагається написати другу рецензію")]
        [NUnit.Framework.CategoryAttribute("us-402")]
        [NUnit.Framework.CategoryAttribute("negative-path")]
        [NUnit.Framework.CategoryAttribute("brl-4")]
        public async System.Threading.Tasks.Task КористувачНамагаєтьсяНаписатиДругуРецензію()
        {
            string[] tagsOfScenario = new string[] {
                    "us-402",
                    "negative-path",
                    "brl-4"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Користувач намагається написати другу рецензію", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Користувач \"user\" авторизований і знаходиться на \"/media/2\" (Dune)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.AndAsync("\"user\" вже писав рецензію на \"Dune\" (Id: 2)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("Він бачить свою вже існуючу рецензію", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Він бачить кнопку \"Редагувати\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він НЕ бачить форми для створення нової рецензії", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Користувач лайкає рецензію")]
        [NUnit.Framework.CategoryAttribute("us-403")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task КористувачЛайкаєРецензію()
        {
            string[] tagsOfScenario = new string[] {
                    "us-403",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Користувач лайкає рецензію", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Користувач \"user\" авторизований і знаходиться на \"/media/2\" (Dune)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.AndAsync("\"user\" ще не лайкнув \"review_1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("\"review_1\" має \"10\" вподобайок", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.WhenAsync("Він натискає \"Вподобати\" (Like) на \"review_1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Лічильник вподобайок \"review_1\" стає \"11\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Кнопка змінює стан на \"Вподобано\" (Liked)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Користувач знімає вподобайку (Unlike)")]
        [NUnit.Framework.CategoryAttribute("us-403")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task КористувачЗнімаєВподобайкуUnlike()
        {
            string[] tagsOfScenario = new string[] {
                    "us-403",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Користувач знімає вподобайку (Unlike)", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Користувач \"user\" авторизований і знаходиться на \"/media/2\" (Dune)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.AndAsync("\"user\" вже лайкнув \"review_1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("\"review_1\" має \"11\" вподобайок", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.WhenAsync("Він натискає \"Вподобано\" (Liked) на \"review_1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Лічильник вподобайок \"review_1\" стає \"10\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Кнопка змінює стан на \"Вподобати\" (Like)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Користувач пише новий коментар до рецензії (Рівень 0)")]
        [NUnit.Framework.CategoryAttribute("us-404")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task КористувачПишеНовийКоментарДоРецензіїРівень0()
        {
            string[] tagsOfScenario = new string[] {
                    "us-404",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Користувач пише новий коментар до рецензії (Рівень 0)", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Користувач \"user\" авторизований і знаходиться на \"/media/2\" (Dune)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Він вводить \"Мій коментар рівня 0\" у поле коментування під \"review_1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.AndAsync("Він натискає \"Відправити\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("\"Мій коментар рівня 0\" з\'являється у списку коментарів під \"review_1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Користувач відповідає на коментар (Рівень 1)")]
        [NUnit.Framework.CategoryAttribute("us-405")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task КористувачВідповідаєНаКоментарРівень1()
        {
            string[] tagsOfScenario = new string[] {
                    "us-405",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Користувач відповідає на коментар (Рівень 1)", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Користувач \"user\" авторизований і бачить \"comment_1\" (від \"other_user\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Він натискає \"Відповісти\" біля \"comment_1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.AndAsync("Він вводить \"Моя відповідь рівня 1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він натискає \"Відправити\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("\"Моя відповідь рівня 1\" з\'являється під \"comment_1\" (з візуальним відступом)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Користувач не може відповісти на відповідь (Немає Рівня 2)")]
        [NUnit.Framework.CategoryAttribute("us-406")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task КористувачНеМожеВідповістиНаВідповідьНемаєРівня2()
        {
            string[] tagsOfScenario = new string[] {
                    "us-406",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Користувач не може відповісти на відповідь (Немає Рівня 2)", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Користувач \"user\" авторизований", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.AndAsync("Існує \"reply_1\" (відповідь Рівня 1) на \"comment_1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.WhenAsync("Користувач \"user\" дивиться на \"reply_1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Він НЕ бачить кнопку \"Відповісти\" біля \"reply_1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Він бачить кнопку \"Відповісти\" тільки біля \"comment_1\" (Рівень 0)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Гість намагається взаємодіяти з рецензією")]
        [NUnit.Framework.CategoryAttribute("us-407")]
        [NUnit.Framework.CategoryAttribute("negative-path")]
        public async System.Threading.Tasks.Task ГістьНамагаєтьсяВзаємодіятиЗРецензією()
        {
            string[] tagsOfScenario = new string[] {
                    "us-407",
                    "negative-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Гість намагається взаємодіяти з рецензією", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Гість (неавторизований) знаходиться на \"/media/2\" (Dune)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Гість натискає \"Вподобати\" на \"review_1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Його перенаправляє на сторінку \"/login\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Система показує повідомлення \"Ви повинні увійти, щоб виконати цю дію\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Гість намагається написати коментар")]
        [NUnit.Framework.CategoryAttribute("us-407")]
        [NUnit.Framework.CategoryAttribute("negative-path")]
        public async System.Threading.Tasks.Task ГістьНамагаєтьсяНаписатиКоментар()
        {
            string[] tagsOfScenario = new string[] {
                    "us-407",
                    "negative-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Гість намагається написати коментар", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Гість (неавторизований) знаходиться на \"/media/2\" (Dune)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Гість намагається ввести текст у поле коментування під \"review_1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Поле коментування неактивне (або при кліку перенаправляє на \"/login\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Він бачить повідомлення \"Увійдіть, щоб залишати коментарі\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Користувач пропонує відсутній переклад")]
        [NUnit.Framework.CategoryAttribute("us-408")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task КористувачПропонуєВідсутнійПереклад()
        {
            string[] tagsOfScenario = new string[] {
                    "us-408",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Користувач пропонує відсутній переклад", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Користувач \"user\" знаходиться на сторінці \"/media/3\" (Inception)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.AndAsync("Для \"Inception\" (Id: 3) відсутній український переклад", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.WhenAsync("Він натискає кнопку \"Запропонувати переклад\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.AndAsync("Він обирає мову \"Українська\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він вводить \"Назва\": \"Початок\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він вводить \"Опис\": \"Фільм про сни...\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він натискає \"Надіслати на модерацію\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("Система створює запис у `MediaTranslations` (MediaId: 3, Lang: \"uk\", Title: \"Поча" +
                        "ток\", Status: \"Pending\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Він бачить повідомлення \"Дякуємо, ваш переклад відправлено на модерацію\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Користувач намагається запропонувати переклад, який вже існує")]
        [NUnit.Framework.CategoryAttribute("us-408")]
        [NUnit.Framework.CategoryAttribute("negative-path")]
        public async System.Threading.Tasks.Task КористувачНамагаєтьсяЗапропонуватиПерекладЯкийВжеІснує()
        {
            string[] tagsOfScenario = new string[] {
                    "us-408",
                    "negative-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Користувач намагається запропонувати переклад, який вже існує", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Користувач \"user\" знаходиться на сторінці \"/media/2\" (Dune)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.AndAsync("Для \"Dune\" (Id: 2) вже існує схвалений переклад \"Дюна\" (Lang: \"uk\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("Він НЕ бачить кнопки \"Запропонувати переклад\" для мови \"Українська\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
