// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:4.0.0.0
//      SpecFlow Generator Version:4.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TrackListTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Статуси перегляду (Трекінг)")]
    [NUnit.Framework.CategoryAttribute("epic5")]
    [NUnit.Framework.CategoryAttribute("tracking")]
    public partial class СтатусиПереглядуТрекінгFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "epic5",
                "tracking"};
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerForAssembly(null, NUnit.Framework.TestContext.CurrentContext.WorkerId);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("uk-UA"), "Features", "Статуси перегляду (Трекінг)", "  Як Авторизований користувач,\r\n  Я хочу мати можливість додавати медіа-контент д" +
                    "о особистих статусів перегляду\r\n  Щоб відстежувати свій прогрес споживання медіа" +
                    ".", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            await testRunner.GivenAsync("В базі даних існує користувач \"user\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
            await testRunner.AndAsync("В базі даних існує медіа \"Dune\" (Id: 2)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("В базі даних існує медіа \"Cyberpunk Edgerunners\" (Id: 4, Тип: Серіал)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("Користувач \"user\" авторизований в системі", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Користувач додає медіа до списку статусів")]
        [NUnit.Framework.CategoryAttribute("us-501")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task КористувачДодаєМедіаДоСпискуСтатусів()
        {
            string[] tagsOfScenario = new string[] {
                    "us-501",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Користувач додає медіа до списку статусів", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Користувач \"user\" знаходиться на сторінці \"/media/2\" (Dune)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.AndAsync("\"Dune\" (Id: 2) ще не має статусу для \"user\"-а", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("На сторінці відображається \"Кнопка Статусу\" з текстом \"відмітити статус\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.WhenAsync("Він натискає на \"Кнопку Статусу\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.AndAsync("У випадаючому меню, що з\'явилося, він обирає статус \"Заплановано\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("Система (бекенд) отримує запит на створення запису в `TrackingStatus` (UserId: \"u" +
                        "ser\", MediaId: 2, Status: \"Planned\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("\"Кнопка Статусу\" на сторінці медіа змінює свій текст на \"У планах\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Користувач змінює статус медіа")]
        [NUnit.Framework.CategoryAttribute("us-501")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        [NUnit.Framework.CategoryAttribute("brl-3")]
        public async System.Threading.Tasks.Task КористувачЗмінюєСтатусМедіа()
        {
            string[] tagsOfScenario = new string[] {
                    "us-501",
                    "happy-path",
                    "brl-3"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Користувач змінює статус медіа", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Користувач \"user\" вже додав \"Dune\" (Id: 2) до статусу \"Заплановано\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.AndAsync("На сторінці \"/media/2\" (Dune) відображається \"Кнопка Статусу\" з текстом \"У планах" +
                        "\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.WhenAsync("Користувач \"user\" натискає на \"Кнопку Статусу\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.AndAsync("У випадаючому меню він обирає новий статус \"Переглянуто\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("Система (бекенд) отримує запит на оновлення запису (Status: \"Completed\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("В базі даних існує лише один запис для пари (UserId: \"user\", MediaId: 2)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("\"Кнопка Статусу\" на сторінці медіа змінює свій текст на \"Переглянуто\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Користувач закриває випадаюче меню (клік поза)")]
        [NUnit.Framework.CategoryAttribute("us-501")]
        [NUnit.Framework.CategoryAttribute("ui-behavior")]
        [NUnit.Framework.CategoryAttribute("frontend")]
        public async System.Threading.Tasks.Task КористувачЗакриваєВипадаючеМенюКлікПоза()
        {
            string[] tagsOfScenario = new string[] {
                    "us-501",
                    "ui-behavior",
                    "frontend"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Користувач закриває випадаюче меню (клік поза)", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Користувач \"user\" авторизований і бачить \"Кнопку Статусу\" з текстом \"відмітити ст" +
                        "атус\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Він натискає на \"Кнопку Статусу\", і випадаюче меню з\'являється", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.AndAsync("Він натискає на будь-яке місце на сторінці поза межами меню", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("Випадаюче меню закривається", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Система (бекенд) НЕ отримує жодного запиту", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Користувач обирає той самий статус")]
        [NUnit.Framework.CategoryAttribute("us-501")]
        [NUnit.Framework.CategoryAttribute("ui-behavior")]
        [NUnit.Framework.CategoryAttribute("frontend")]
        public async System.Threading.Tasks.Task КористувачОбираєТойСамийСтатус()
        {
            string[] tagsOfScenario = new string[] {
                    "us-501",
                    "ui-behavior",
                    "frontend"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Користувач обирає той самий статус", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Користувач \"user\" вже додав \"Dune\" (Id: 2) до статусу \"Заплановано\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.AndAsync("\"Кнопка Статусу\" показує текст \"У планах\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.WhenAsync("Він натискає на \"Кнопку Статусу\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.AndAsync("У випадаючому меню він обирає статус \"Заплановано\" (той самий, що й активний)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("Випадаюче меню закривається", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Система (бекенд) НЕ отримує жодного запиту", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("\"Кнопка Статусу\" продовжує показувати текст \"У планах\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Користувач оновлює прогрес перегляду серіалу")]
        [NUnit.Framework.CategoryAttribute("us-502")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task КористувачОновлюєПрогресПереглядуСеріалу()
        {
            string[] tagsOfScenario = new string[] {
                    "us-502",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Користувач оновлює прогрес перегляду серіалу", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Користувач \"user\" додав \"Cyberpunk Edgerunners\" (Id: 4) до статусу \"Дивлюся\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Він переходить на сторінку свого профілю (вкладка \"Трекінг\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.AndAsync("Він бачить \"Cyberpunk Edgerunners\" у списку \"Дивлюся\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він вводить \"5\" у поле \"Поточний епізод\" для \"Cyberpunk Edgerunners\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він натискає \"Зберегти\" (або відбувається автозбереження)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("Система (бекенд) оновлює запис у `TrackingStatus` (MediaId: 4), додавши \"Progress" +
                        ": 5\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
