// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:4.0.0.0
//      SpecFlow Generator Version:4.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TrackListTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Модерація контенту")]
    [NUnit.Framework.CategoryAttribute("epic6")]
    [NUnit.Framework.CategoryAttribute("moderation")]
    public partial class МодераціяКонтентуFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "epic6",
                "moderation"};
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerForAssembly(null, NUnit.Framework.TestContext.CurrentContext.WorkerId);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("uk-UA"), "Features", "Модерація контенту", "  Як Користувач,\r\n  Я хочу мати можливість скаржитися (репортити) на образливий к" +
                    "онтент.\r\n  Як Модератор,\r\n  Я хочу бачити чергу скарг та чергу запропонованих пе" +
                    "рекладів,\r\n  Щоб підтримувати порядок та якість контенту на платформі.", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            await testRunner.GivenAsync("Існує \"user\" (Роль: Користувач)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
            await testRunner.GivenAsync("Існує \"moderator\" (Роль: Модератор) з ID \"moderator-uuid-123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
            await testRunner.GivenAsync("Існує медіа \"Dune\" (Id: 2)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
            await testRunner.GivenAsync("\"user\" написав рецензію \"review_1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
            await testRunner.GivenAsync("\"user\" запропонував переклад \"Дюнааа\" (Lang: \"uk\") для \"Dune\" (Id: 2) зі статусом" +
                    " \"Pending\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Користувач скаржиться на рецензію")]
        [NUnit.Framework.CategoryAttribute("us-601")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task КористувачСкаржитьсяНаРецензію()
        {
            string[] tagsOfScenario = new string[] {
                    "us-601",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Користувач скаржиться на рецензію", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Користувач \"user\" авторизований і бачить \"review_1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Він натискає \"Поскаржитись\" на \"review_1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.AndAsync("Він обирає причину \"Спам\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він натискає \"Надіслати скаргу\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("Система створює запис у `Reports` (TargetId: \"review_1_id\", Status: \"Pending\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Користувач бачить повідомлення \"Скаргу надіслано\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Модератор обробляє скаргу (видаляє контент)")]
        [NUnit.Framework.CategoryAttribute("us-602")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task МодераторОбробляєСкаргуВидаляєКонтент()
        {
            string[] tagsOfScenario = new string[] {
                    "us-602",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Модератор обробляє скаргу (видаляє контент)", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("\"moderator\" (ID: \"moderator-uuid-123\") авторизований і знаходиться в \"Панелі моде" +
                        "ратора\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.AndAsync("Він бачить скаргу \"report_1\" на \"review_1\" (Статус: \"Pending\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.WhenAsync("Він натискає \"Видалити рецензію\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Поле \"DeletedAt\" для \"review_1\" встановлюється на поточний час", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Статус скарги \"report_1\" оновлюється на \"Resolved_Deleted\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Поле \"ProcessedByUserId\" для скарги \"report_1\" встановлюється на \"moderator-uuid-" +
                        "123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Модератор відхиляє скаргу (контент в нормі)")]
        [NUnit.Framework.CategoryAttribute("us-602")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task МодераторВідхиляєСкаргуКонтентВНормі()
        {
            string[] tagsOfScenario = new string[] {
                    "us-602",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Модератор відхиляє скаргу (контент в нормі)", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("\"moderator\" (ID: \"moderator-uuid-123\") авторизований і бачить скаргу \"report_1\" (" +
                        "Статус: \"Pending\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Він натискає \"Відхилити скаргу\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Поле \"DeletedAt\" для \"review_1\" залишається \"null\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Статус скарги \"report_1\" оновлюється на \"Resolved_Dismissed\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Поле \"ProcessedByUserId\" для скарги \"report_1\" встановлюється на \"moderator-uuid-" +
                        "123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Модератор схвалює запропонований переклад")]
        [NUnit.Framework.CategoryAttribute("us-603")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task МодераторСхвалюєЗапропонованийПереклад()
        {
            string[] tagsOfScenario = new string[] {
                    "us-603",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Модератор схвалює запропонований переклад", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("\"moderator\" (ID: \"moderator-uuid-123\") авторизований і знаходиться в \"Панелі моде" +
                        "ратора\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Він переходить у чергу \"Запропоновані переклади\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.AndAsync("Він бачить запит \"translation_1\" (Назва: \"Дюнааа\") зі статусом \"Pending\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він натискає кнопку \"Схвалити\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("Статус \"translation_1\" оновлюється на \"Approved\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Поле \"ProcessedByUserId\" для \"translation_1\" встановлюється на \"moderator-uuid-12" +
                        "3\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Запит зникає з черги модерації", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Модератор відхиляє запропонований переклад")]
        [NUnit.Framework.CategoryAttribute("us-603")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task МодераторВідхиляєЗапропонованийПереклад()
        {
            string[] tagsOfScenario = new string[] {
                    "us-603",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Модератор відхиляє запропонований переклад", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("\"moderator\" (ID: \"moderator-uuid-123\") авторизований і бачить запит \"translation_" +
                        "1\" (Статус: \"Pending\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Він натискає кнопку \"Відхилити\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Статус \"translation_1\" оновлюється на \"Rejected\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Поле \"ProcessedByUserId\" для \"translation_1\" встановлюється на \"moderator-uuid-12" +
                        "3\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Запит зникає з черги модерації", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
