// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:4.0.0.0
//      SpecFlow Generator Version:4.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TrackListTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Адміністрування системи")]
    [NUnit.Framework.CategoryAttribute("epic7")]
    [NUnit.Framework.CategoryAttribute("admin")]
    public partial class АдмініструванняСистемиFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "epic7",
                "admin"};
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerForAssembly(null, NUnit.Framework.TestContext.CurrentContext.WorkerId);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("uk-UA"), "Features", "Адміністрування системи", "  Як Адміністратор,\r\n  Я хочу мати повний контроль (CRUD) над основними сутностям" +
                    "и системи (користувачі, медіа)\r\n  Та переглядати детальну статистику\r\n  Щоб керу" +
                    "вати платформою та аналізувати її ефективність.", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            await testRunner.GivenAsync("Існує \"admin\" (Роль: Адміністратор) з ID \"admin-uuid-001\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
            await testRunner.GivenAsync("Існує \"user\" (Роль: Користувач) з ID \"user-uuid-123\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
            await testRunner.GivenAsync("Існує \"moderator\" (Роль: Модератор) з ID \"moderator-uuid-456\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
            await testRunner.AndAsync("Існує медіа \"Dune\" (Id: 2)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("В `MediaTranslations` існує \"translation_1\" (MediaId: 2, Lang: \"uk\", Title: \"Дюна" +
                    "\", Status: \"Official\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Адміністратор змінює роль користувача (Підвищення до Модератора)")]
        [NUnit.Framework.CategoryAttribute("us-701")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task АдміністраторЗмінюєРольКористувачаПідвищенняДоМодератора()
        {
            string[] tagsOfScenario = new string[] {
                    "us-701",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Адміністратор змінює роль користувача (Підвищення до Модератора)", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("\"admin\" (ID: \"admin-uuid-001\") авторизований і знаходиться в \"Панелі адміністрато" +
                        "ра\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Він переходить у \"Керування користувачами\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.AndAsync("Він знаходить \"user\" (ID: \"user-uuid-123\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він натискає \"Змінити роль\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він обирає \"Модератор\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він натискає \"Зберегти\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("Поле \"Role\" для \"user-uuid-123\" в базі даних оновлюється на \"Moderator\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Поле \"UpdatedAt\" для \"user-uuid-123\" оновлено", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Адміністратор (м\'яко) видаляє користувача")]
        [NUnit.Framework.CategoryAttribute("us-701")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        [NUnit.Framework.CategoryAttribute("soft-delete")]
        public async System.Threading.Tasks.Task АдміністраторМякоВидаляєКористувача()
        {
            string[] tagsOfScenario = new string[] {
                    "us-701",
                    "happy-path",
                    "soft-delete"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Адміністратор (м\'яко) видаляє користувача", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("\"admin\" (ID: \"admin-uuid-001\") авторизований і знаходиться в \"Панелі адміністрато" +
                        "ра\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Він знаходить \"user\" (ID: \"user-uuid-123\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.AndAsync("Він натискає \"Видалити користувача\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він підтверджує дію", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("Поле \"DeletedAt\" для \"user-uuid-123\" в базі даних встановлюється на поточний час", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Користувач \"user-uuid-123\" більше не може авторизуватися", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("\"user-uuid-123\" зникає зі списків у UI (завдяки Global Query Filter)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Адміністратор редагує схвалений або офіційний переклад")]
        [NUnit.Framework.CategoryAttribute("us-702")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task АдміністраторРедагуєСхваленийАбоОфіційнийПереклад()
        {
            string[] tagsOfScenario = new string[] {
                    "us-702",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Адміністратор редагує схвалений або офіційний переклад", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("\"admin\" (ID: \"admin-uuid-001\") авторизований і знаходиться в \"Панелі адміністрато" +
                        "ра\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Він переходить у \"Керування медіа\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.AndAsync("Він знаходить \"Dune\" (Id: 2)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він бачить переклад \"translation_1\" (Lang: \"uk\", Title: \"Дюна\", Status: \"Official" +
                        "\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він натискає \"Редагувати\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він змінює \"Title\" на \"Дюна: Частина перша\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він натискає \"Зберегти\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("Запис \"translation_1\" у `MediaTranslations` оновлено", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Поле \"ProcessedByUserId\" для \"translation_1\" встановлено на \"admin-uuid-001\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Адміністратор (м\'яко) видаляє медіа-контент")]
        [NUnit.Framework.CategoryAttribute("us-702")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        [NUnit.Framework.CategoryAttribute("soft-delete")]
        public async System.Threading.Tasks.Task АдміністраторМякоВидаляєМедіа_Контент()
        {
            string[] tagsOfScenario = new string[] {
                    "us-702",
                    "happy-path",
                    "soft-delete"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Адміністратор (м\'яко) видаляє медіа-контент", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("\"admin\" (ID: \"admin-uuid-001\") авторизований і знаходиться в \"Панелі адміністрато" +
                        "ра\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Він знаходить \"Dune\" (Id: 2)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.AndAsync("Він натискає \"Видалити медіа\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Він підтверджує дію", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("Поле \"DeletedAt\" для \"Dune\" (Id: 2) в базі даних встановлюється на поточний час", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("\"Dune\" зникає з пошуку та зі списків (завдяки Global Query Filter)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Адміністратор переглядає статистику")]
        [NUnit.Framework.CategoryAttribute("us-703")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task АдміністраторПереглядаєСтатистику()
        {
            string[] tagsOfScenario = new string[] {
                    "us-703",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Адміністратор переглядає статистику", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("\"admin\" авторизований і знаходиться в \"Панелі адміністратора\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Він переходить у \"Статистика\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Він бачить віджети: \"Нові користувачі (за 30 днів)\", \"Кількість рецензій (за 30 д" +
                        "нів)\", \"Найпопулярніші жанри\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Адміністратор фільтрує статистику та завантажує звіт")]
        [NUnit.Framework.CategoryAttribute("us-703")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task АдміністраторФільтруєСтатистикуТаЗавантажуєЗвіт()
        {
            string[] tagsOfScenario = new string[] {
                    "us-703",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Адміністратор фільтрує статистику та завантажує звіт", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("\"admin\" знаходиться на сторінці \"Статистика\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Він обирає проміжок часу (наприклад, \"з 01.10.2025 по 31.10.2025\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.AndAsync("Він натискає \"Оновити\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("Віджети оновлюють дані відповідно до обраного проміжку", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Він натискає \"Завантажити звіт\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.ThenAsync("Система генерує та завантажує файл (.csv або .xlsx) зі статистикою", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
