// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:4.0.0.0
//      SpecFlow Generator Version:4.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TrackListTests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "4.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Мультимовний пошук та кешування медіа-контенту")]
    [NUnit.Framework.CategoryAttribute("epic9")]
    [NUnit.Framework.CategoryAttribute("search")]
    public partial class МультимовнийПошукТаКешуванняМедіа_КонтентуFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "epic9",
                "search"};
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerForAssembly(null, NUnit.Framework.TestContext.CurrentContext.WorkerId);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("uk-UA"), "Features", "Мультимовний пошук та кешування медіа-контенту", "  Як Користувач (або Гість),\r\n  Я хочу мати можливість шукати медіа-контент на бу" +
                    "дь-якій мові\r\n  Щоб завжди знаходити потрібне медіа, незалежно від мови введення" +
                    ".", ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            await testRunner.GivenAsync("Система підключена до зовнішнього API (наприклад, TMDB)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
            await testRunner.AndAsync("В таблиці `Media` існує запис (Id: 1, ExternalApiId: \"tmdb-550\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("В `MediaTranslations` існує: (MediaId: 1, Lang: \"en\", Title: \"Fight Club\", Status" +
                    ": \"Official\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("В `MediaTranslations` існує: (MediaId: 1, Lang: \"uk\", Title: \"Бійцівський клуб\", " +
                    "Status: \"Approved\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("В `MediaTranslations` існує: (MediaId: 1, Lang: \"uk\", Title: \"Клуб забіяк\", Statu" +
                    "s: \"Pending\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("В зовнішньому API (TMDB) існує медіа \"Dune\" (ExternalApiId: \"tmdb-438631\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("\"Dune\" (ExternalApiId: \"tmdb-438631\") ще не існує в локальній таблиці `Media`", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            await testRunner.AndAsync("В таблиці `Media` існує \"Deleted Movie\" (Id: 3, DeletedAt: \"2025-10-10T10:00:00Z\"" +
                    ")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Користувач шукає медіа та бачить зведені результати")]
        [NUnit.Framework.CategoryAttribute("us-901")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task КористувачШукаєМедіаТаБачитьЗведеніРезультати()
        {
            string[] tagsOfScenario = new string[] {
                    "us-901",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Користувач шукає медіа та бачить зведені результати", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Гість знаходиться у рядку пошуку", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Він вводить запит \"Dune\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Бекенд опитує і локальну БД (по `MediaTranslations`), і зовнішнє API (TMDB)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Назва",
                            "Джерело"});
                table2.AddRow(new string[] {
                            "Dune",
                            "(з зовнішнього API)"});
                await testRunner.AndAsync("Система показує список результатів, що містить:", ((string)(null)), table2, "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Користувач шукає медіа за українським перекладом (з локальної БД)")]
        [NUnit.Framework.CategoryAttribute("us-901")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task КористувачШукаєМедіаЗаУкраїнськимПерекладомЗЛокальноїБД()
        {
            string[] tagsOfScenario = new string[] {
                    "us-901",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Користувач шукає медіа за українським перекладом (з локальної БД)", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Гість знаходиться у рядку пошуку", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Він вводить запит \"Бійцівський\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Він бачить \"Бійцівський клуб\" (Id: 1) у результатах пошуку", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Пошук не знаходить не-схвалені або видалені медіа")]
        [NUnit.Framework.CategoryAttribute("us-901")]
        [NUnit.Framework.CategoryAttribute("negative-path")]
        public async System.Threading.Tasks.Task ПошукНеЗнаходитьНе_СхваленіАбоВидаленіМедіа()
        {
            string[] tagsOfScenario = new string[] {
                    "us-901",
                    "negative-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Пошук не знаходить не-схвалені або видалені медіа", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Гість знаходиться у рядку пошуку", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.WhenAsync("Він вводить запит \"Клуб забіяк\" (який має статус \'Pending\')", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Він НЕ бачить \"Бійцівський клуб\" у результатах пошуку", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.WhenAsync("Він вводить запит \"Deleted Movie\" (який має `DeletedAt != null`)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Він НЕ бачить \"Deleted Movie\" у результатах пошуку", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Користувач відкриває сторінку медіа, якого ще немає в локальній БД")]
        [NUnit.Framework.CategoryAttribute("us-902")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task КористувачВідкриваєСторінкуМедіаЯкогоЩеНемаєВЛокальнійБД()
        {
            string[] tagsOfScenario = new string[] {
                    "us-902",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Користувач відкриває сторінку медіа, якого ще немає в локальній БД", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Користувач бачить \"Dune\" (ExternalApiId: \"tmdb-438631\") у результатах пошуку", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.AndAsync("Запис \"tmdb-438631\" ще не існує в локальній таблиці `Media`", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.WhenAsync("Він натискає на \"Dune\" (переходить на \"/media/tmdb-438631\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Бекенд звертається до зовнішнього API за повною інформацією про \"tmdb-438631\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Бекенд створює новий запис (з новим Guid v7) в таблиці `Media` (з `ExternalApiId`" +
                        " = \"tmdb-438631\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Бекенд створює запис в `MediaTranslations` (Lang: \"en\", Title: \"Dune\", Status: \"O" +
                        "fficial\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Бекенд створює запис в `MediaTranslations` (Lang: \"uk\", Title: \"Дюна\", Status: \"O" +
                        "fficial\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Користувач бачить повну сторінку \"Дюна\" (або \"Dune\", залежно від мови)", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Користувач відкриває сторінку медіа, яке вже є в кеші")]
        [NUnit.Framework.CategoryAttribute("us-902")]
        [NUnit.Framework.CategoryAttribute("happy-path")]
        public async System.Threading.Tasks.Task КористувачВідкриваєСторінкуМедіаЯкеВжеЄВКеші()
        {
            string[] tagsOfScenario = new string[] {
                    "us-902",
                    "happy-path"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Користувач відкриває сторінку медіа, яке вже є в кеші", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("Користувач бачить \"Бійцівський клуб\" (Id: 1) у результатах пошуку", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
                await testRunner.AndAsync("\"Бійцівський клуб\" (Id: 1) вже існує в локальній таблиці `Media`", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.WhenAsync("Він натискає на \"Бійцівський клуб\" (переходить на \"/media/1\")", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Коли ");
                await testRunner.ThenAsync("Бекенд НЕ звертається до зовнішнього API", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тоді ");
                await testRunner.AndAsync("Бекенд миттєво повертає дані про \"Id: 1\" з локальної таблиці `Media`", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
                await testRunner.AndAsync("Користувач бачить повну сторінку \"Бійцівський клуб\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "І ");
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
